# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Parcelador_COLPOS
                                 A QGIS plugin
 Optimización de trazado de unidades de producción para áreas determinadas 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-04-16
        copyright            : (C) 2026 by Manuel Vichique A
        email                : vichique.manuel@colpos.mx
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Parcelador_COLPOS class from file Parcelador_COLPOS.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .diseno_agricola import Parcelador_COLPOS
    return Parcelador_COLPOS(iface)
